// Auto-generated SQL schema for Uber clone
export const SQL_STATEMENTS: string[] = [
  `CREATE TABLE "User" ( "id" TEXT NOT NULL PRIMARY KEY, "name" TEXT NOT NULL, "email" TEXT NOT NULL, "phone" TEXT NOT NULL, "password" TEXT NOT NULL, "city" TEXT, "region" TEXT, "avatar" TEXT, "isVerified" BOOLEAN NOT NULL DEFAULT false, "isAdmin" BOOLEAN NOT NULL DEFAULT false, "isDriver" BOOLEAN NOT NULL DEFAULT false, "isBlocked" BOOLEAN NOT NULL DEFAULT false, "blockedAt" DATETIME, "blockReason" TEXT, "walletBalance" REAL NOT NULL DEFAULT 0, "rating" REAL NOT NULL DEFAULT 5, "tripsCount" INTEGER NOT NULL DEFAULT 0, "currentLat" REAL, "currentLng" REAL, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" DATETIME NOT NULL )`,
  `CREATE TABLE "Driver" ( "id" TEXT NOT NULL PRIMARY KEY, "userId" TEXT NOT NULL, "carModel" TEXT NOT NULL, "carPlate" TEXT NOT NULL, "carColor" TEXT NOT NULL, "carYear" INTEGER, "licenseNumber" TEXT NOT NULL, "licenseExpiry" DATETIME, "isOnline" BOOLEAN NOT NULL DEFAULT false, "isVerified" BOOLEAN NOT NULL DEFAULT false, "isApproved" BOOLEAN NOT NULL DEFAULT false, "approvalStatus" TEXT NOT NULL DEFAULT 'pending', "rejectionReason" TEXT, "rating" REAL NOT NULL DEFAULT 5, "tripsCount" INTEGER NOT NULL DEFAULT 0, "earnings" REAL NOT NULL DEFAULT 0, "currentLat" REAL, "currentLng" REAL, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" DATETIME NOT NULL, CONSTRAINT "Driver_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE CASCADE ON UPDATE CASCADE )`,
  `CREATE TABLE "DriverDocument" ( "id" TEXT NOT NULL PRIMARY KEY, "driverId" TEXT NOT NULL, "type" TEXT NOT NULL, "fileName" TEXT NOT NULL, "fileUrl" TEXT NOT NULL, "fileData" TEXT, "fileSize" INTEGER, "mimeType" TEXT, "status" TEXT NOT NULL DEFAULT 'pending', "uploadedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "DriverDocument_driverId_fkey" FOREIGN KEY ("driverId") REFERENCES "Driver" ("id") ON DELETE CASCADE ON UPDATE CASCADE )`,
  `CREATE TABLE "Trip" ( "id" TEXT NOT NULL PRIMARY KEY, "userId" TEXT NOT NULL, "driverId" TEXT, "serviceType" TEXT NOT NULL DEFAULT 'ride', "fromAddress" TEXT NOT NULL, "fromCity" TEXT, "toAddress" TEXT NOT NULL, "toCity" TEXT, "fromLat" REAL, "fromLng" REAL, "toLat" REAL, "toLng" REAL, "distance" REAL NOT NULL DEFAULT 0, "duration" INTEGER NOT NULL DEFAULT 0, "price" REAL NOT NULL DEFAULT 0, "finalPrice" REAL NOT NULL DEFAULT 0, "basePrice" REAL NOT NULL DEFAULT 0, "surgeMultiplier" REAL NOT NULL DEFAULT 1, "status" TEXT NOT NULL DEFAULT 'pending', "paymentMethod" TEXT NOT NULL DEFAULT 'cash', "paymentStatus" TEXT NOT NULL DEFAULT 'pending', "cancellationLocked" BOOLEAN NOT NULL DEFAULT false, "cancellationRequest" TEXT, "cancellationReason" TEXT, "rating" INTEGER, "review" TEXT, "driverArrivedAt" DATETIME, "startedAt" DATETIME, "completedAt" DATETIME, "cancelledAt" DATETIME, "cancelReason" TEXT, "waitingMinutes" INTEGER NOT NULL DEFAULT 0, "lateFee" REAL NOT NULL DEFAULT 0, "freeWaitingMinutes" INTEGER NOT NULL DEFAULT 3, "lateFeePerMinute" REAL NOT NULL DEFAULT 2, "cashReceived" REAL, "unpaidAmount" REAL NOT NULL DEFAULT 0, "paymentConfirmed" BOOLEAN NOT NULL DEFAULT false, "unpaidReportedToAdmin" BOOLEAN NOT NULL DEFAULT false, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, "acceptedAt" DATETIME, CONSTRAINT "Trip_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE RESTRICT ON UPDATE CASCADE )`,
  `CREATE TABLE "Transaction" ( "id" TEXT NOT NULL PRIMARY KEY, "userId" TEXT NOT NULL, "type" TEXT NOT NULL, "amount" REAL NOT NULL, "description" TEXT NOT NULL, "status" TEXT NOT NULL DEFAULT 'completed', "tripId" TEXT, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "Transaction_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE RESTRICT ON UPDATE CASCADE )`,
  `CREATE TABLE "BankAccount" ( "id" TEXT NOT NULL PRIMARY KEY, "userId" TEXT NOT NULL, "bankName" TEXT NOT NULL, "accountName" TEXT NOT NULL, "iban" TEXT, "accountNumber" TEXT, "accountType" TEXT NOT NULL DEFAULT 'bank', "paypalEmail" TEXT, "isDefault" BOOLEAN NOT NULL DEFAULT false, "isVerified" BOOLEAN NOT NULL DEFAULT false, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "BankAccount_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE RESTRICT ON UPDATE CASCADE )`,
  `CREATE TABLE "ChatMessage" ( "id" TEXT NOT NULL PRIMARY KEY, "tripId" TEXT NOT NULL, "senderId" TEXT NOT NULL, "receiverId" TEXT NOT NULL, "message" TEXT, "messageType" TEXT NOT NULL DEFAULT 'text', "fileData" TEXT, "fileName" TEXT, "isRead" BOOLEAN NOT NULL DEFAULT false, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP )`,
  `CREATE TABLE "Notification" ( "id" TEXT NOT NULL PRIMARY KEY, "userId" TEXT NOT NULL, "title" TEXT NOT NULL, "message" TEXT NOT NULL, "type" TEXT NOT NULL DEFAULT 'system', "isRead" BOOLEAN NOT NULL DEFAULT false, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "Notification_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE RESTRICT ON UPDATE CASCADE )`,
  `CREATE TABLE "ServicePrice" ( "id" TEXT NOT NULL PRIMARY KEY, "serviceId" TEXT NOT NULL, "name" TEXT NOT NULL, "basePrice" REAL NOT NULL DEFAULT 8, "perKm" REAL NOT NULL DEFAULT 1.5, "perMin" REAL NOT NULL DEFAULT 0.25, "minPrice" REAL NOT NULL DEFAULT 12, "seats" INTEGER NOT NULL DEFAULT 4, "isActive" BOOLEAN NOT NULL DEFAULT true, "updatedAt" DATETIME NOT NULL )`,
  `CREATE TABLE "SiteSettings" ( "id" TEXT NOT NULL PRIMARY KEY DEFAULT 'default', "commissionRate" REAL NOT NULL DEFAULT 15, "vatRate" REAL NOT NULL DEFAULT 15, "freeWaitingMin" INTEGER NOT NULL DEFAULT 5, "lateFeePerMin" REAL NOT NULL DEFAULT 1, "supportPhone" TEXT NOT NULL DEFAULT '0575015019', "supportEmail" TEXT NOT NULL DEFAULT 'support@uber.sa', "adminEmail" TEXT NOT NULL DEFAULT 'khalid-alharbi@zohomail.sa', "updatedAt" DATETIME NOT NULL )`,
  `CREATE TABLE "Coupon" ( "id" TEXT NOT NULL PRIMARY KEY, "code" TEXT NOT NULL, "type" TEXT NOT NULL DEFAULT 'fixed', "value" REAL NOT NULL, "minTripPrice" REAL NOT NULL DEFAULT 0, "maxUses" INTEGER NOT NULL DEFAULT 1, "usesCount" INTEGER NOT NULL DEFAULT 0, "isActive" BOOLEAN NOT NULL DEFAULT true, "expiresAt" DATETIME, "createdById" TEXT, "appliedToId" TEXT, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP )`,
  `CREATE UNIQUE INDEX "User_email_key" ON "User"("email")`,
  `CREATE UNIQUE INDEX "User_phone_key" ON "User"("phone")`,
  `CREATE UNIQUE INDEX "Driver_userId_key" ON "Driver"("userId")`,
  `CREATE UNIQUE INDEX "ServicePrice_serviceId_key" ON "ServicePrice"("serviceId")`,
  `CREATE UNIQUE INDEX "Coupon_code_key" ON "Coupon"("code")`,
]